---
version: '3'

services:
  zcash-insight-explorer:
    build: .
    environment:
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_ZMQPORT=$ZCASHD_ZMQPORT
    ports:
      - "3001:3001"

  zcashd:
    image: electriccoinco/zcashd
    environment:
      - ZCASHD_NETWORK=$ZCASHD_NETWORK
      - ZCASHD_LOGIPS=$ZCASHD_LOGIPS
      - ZCASHD_EXPERIMENTALFEATURES=$ZCASHD_EXPERIMENTALFEATURES
      - ZCASHD_GEN=$ZCASHD_GEN
      - ZCASHD_RPCUSER=$ZCASHD_RPCUSER
      - ZCASHD_RPCPASSWORD=$ZCASHD_RPCPASSWORD
      - ZCASHD_RPCBIND=$ZCASHD_RPCBIND
      - ZCASHD_ALLOWIP=$ZCASHD_ALLOWIP
      - ZCASHD_TXINDEX=$ZCASHD_TXINDEX
      - ZCASHD_INSIGHTEXPLORER=$ZCASHD_INSIGHTEXPLORER
      - ZCASHD_ZMQPORT=$ZCASHD_ZMQPORT
      - ZCASHD_ZMQBIND=$ZCASHD_ZMQBIND
    volumes:
      - zcash-params:/srv/zcashd/.zcash-params
      - zcash-insight-explorer:/srv/zcashd/.zcash
volumes:
    zcash-params:
    zcash-insight-explorer: